export const harnessCatalogVersion = "starter-catalog-2026-06";

export const connectorFamilies = [
  {
    id: "usb-breakout",
    manufacturer: "Adafruit",
    name: "USB Breakout",
    category: "Board / breakout",
    sealed: false,
    partCount: 3,
    defaultPartId: "adafruit-5978",
  },
  {
    id: "anderson-powerpole-15-45",
    manufacturer: "Anderson Power",
    name: "Powerpole 15/45",
    category: "Power connector",
    sealed: false,
    partCount: 2,
    defaultPartId: "anderson-1327g6-bk",
  },
  {
    id: "harwin-m20",
    manufacturer: "Harwin",
    name: "DuPont / M20",
    category: "Board-to-wire",
    sealed: false,
    partCount: 4,
    defaultPartId: "harwin-m20-1060600",
  },
  {
    id: "jst-xh",
    manufacturer: "JST",
    name: "XH",
    category: "Wire-to-board",
    sealed: false,
    partCount: 5,
    defaultPartId: "jst-b6b-xh-a",
  },
  {
    id: "molex-microfit-3",
    manufacturer: "Molex",
    name: "Micro-Fit 3.0",
    category: "Wire-to-wire",
    sealed: false,
    partCount: 4,
    defaultPartId: "molex-43025-0400",
  },
  {
    id: "deutsch-dt",
    manufacturer: "TE / Deutsch",
    name: "DT sealed",
    category: "Sealed connector",
    sealed: true,
    partCount: 4,
    defaultPartId: "deutsch-dt04-2p",
  },
];

export const connectorParts = [
  {
    id: "adafruit-5978",
    mpn: "5978",
    manufacturer: "Adafruit",
    familyId: "usb-breakout",
    displayName: "USB Type-C breakout",
    pinCounts: [5],
    defaultPinCount: 5,
    options: ["USB Type-C breakout", "USB 2.0 signal pads"],
    awgRange: [22, 28],
    currentRatingA: 1,
    voltageRatingV: 5,
    compatibleTerminals: [],
    notes: "Breakout board pads usually need soldered leads.",
    visual: "usb-board",
  },
  {
    id: "adafruit-5180",
    mpn: "5180",
    manufacturer: "Adafruit",
    familyId: "usb-breakout",
    displayName: "USB-C plug breakout",
    pinCounts: [6],
    defaultPinCount: 6,
    options: ["USB-C plug breakout", "Signal pads"],
    awgRange: [24, 30],
    currentRatingA: 1,
    voltageRatingV: 5,
    compatibleTerminals: [],
    notes: "Confirm pin naming against the board silkscreen before quote.",
    visual: "usb-board",
  },
  {
    id: "adafruit-6050",
    mpn: "6050",
    manufacturer: "Adafruit",
    familyId: "usb-breakout",
    displayName: "USB-C receptacle breakout",
    pinCounts: [6, 12],
    defaultPinCount: 6,
    options: ["USB-C receptacle breakout", "Power-only pads"],
    awgRange: [24, 30],
    currentRatingA: 1,
    voltageRatingV: 5,
    compatibleTerminals: [],
    notes: "Power-only and data-capable variants need review.",
    visual: "usb-board",
  },
  {
    id: "anderson-1327g6-bk",
    mpn: "1327G6-BK",
    manufacturer: "Anderson Power",
    familyId: "anderson-powerpole-15-45",
    displayName: "Powerpole 15/45 housing, black",
    pinCounts: [1],
    defaultPinCount: 1,
    options: ["1 row, neutral, black"],
    awgRange: [10, 20],
    currentRatingA: 45,
    voltageRatingV: 600,
    compatibleTerminals: ["Powerpole 15/30/45 contacts"],
    notes: "Contact size depends on selected wire gauge.",
    visual: "powerpole",
  },
  {
    id: "anderson-1327g6-red",
    mpn: "1327G6-RED",
    manufacturer: "Anderson Power",
    familyId: "anderson-powerpole-15-45",
    displayName: "Powerpole 15/45 housing, red",
    pinCounts: [1],
    defaultPinCount: 1,
    options: ["1 row, neutral, red"],
    awgRange: [10, 20],
    currentRatingA: 45,
    voltageRatingV: 600,
    compatibleTerminals: ["Powerpole 15/30/45 contacts"],
    notes: "Often paired with black housing for DC power.",
    visual: "powerpole",
  },
  {
    id: "harwin-m20-1060600",
    mpn: "M20-1060600",
    manufacturer: "Harwin",
    familyId: "harwin-m20",
    displayName: "M20 1-row female crimp housing",
    pinCounts: [6],
    defaultPinCount: 6,
    options: ["1 row, female crimp, black"],
    awgRange: [22, 30],
    currentRatingA: 3,
    voltageRatingV: 250,
    compatibleTerminals: ["M20 crimp socket contacts"],
    notes: "Common 2.54 mm pitch housing; mating header must be confirmed.",
    visual: "rect-housing",
  },
  {
    id: "jst-b6b-xh-a",
    mpn: "B6B-XH-A(LF)(SN)",
    manufacturer: "JST",
    familyId: "jst-xh",
    displayName: "XH top-entry header",
    pinCounts: [2, 3, 4, 5, 6, 7, 8],
    defaultPinCount: 6,
    options: ["Top-entry header", "Natural housing mate"],
    awgRange: [22, 28],
    currentRatingA: 3,
    voltageRatingV: 250,
    compatibleTerminals: ["SXH-001T-P0.6 contacts"],
    notes: "Housing, header, and contact direction need match review.",
    visual: "rect-housing",
  },
  {
    id: "molex-43025-0400",
    mpn: "43025-0400",
    manufacturer: "Molex",
    familyId: "molex-microfit-3",
    displayName: "Micro-Fit 3.0 receptacle housing",
    pinCounts: [2, 4, 6, 8],
    defaultPinCount: 4,
    options: ["Dual row receptacle housing", "Black"],
    awgRange: [20, 30],
    currentRatingA: 5,
    voltageRatingV: 600,
    compatibleTerminals: ["Micro-Fit 3.0 crimp terminals"],
    notes: "Terminal plating and keying should be confirmed before quote.",
    visual: "microfit",
  },
  {
    id: "deutsch-dt04-2p",
    mpn: "DT04-2P",
    manufacturer: "TE / Deutsch",
    familyId: "deutsch-dt",
    displayName: "DT 2-pin receptacle housing",
    pinCounts: [2],
    defaultPinCount: 2,
    options: ["Receptacle, 2 pin, gray", "Wedge lock needed"],
    awgRange: [14, 20],
    currentRatingA: 13,
    voltageRatingV: 250,
    compatibleTerminals: ["Size 16 solid contacts", "W2P wedge lock"],
    notes: "Seals and wedge locks are part of the review basis.",
    visual: "sealed-dt",
  },
];

export const midElementTypes = [
  {
    id: "splice",
    label: "Solder splice",
    defaultLabel: "Solder splice, black heatshrink",
    allowedLeftPins: [1, 2, 3, 4],
    allowedRightPins: [1, 2, 3, 4],
    defaultLeftPins: 1,
    defaultRightPins: 4,
    awgRange: [10, 32],
    options: ["Black heatshrink", "Clear heatshrink", "Adhesive-lined heatshrink"],
  },
  {
    id: "cable",
    label: "Cable breakout",
    defaultLabel: "Cable breakout",
    allowedLeftPins: [1, 2, 3, 4, 5, 6],
    allowedRightPins: [1, 2, 3, 4, 5, 6],
    defaultLeftPins: 1,
    defaultRightPins: 2,
    awgRange: [18, 30],
    options: ["Jacketed cable", "Shielded cable", "Twisted pair"],
  },
  {
    id: "fuse",
    label: "Inline fuse",
    defaultLabel: "Inline fuse holder",
    allowedLeftPins: [1],
    allowedRightPins: [1],
    defaultLeftPins: 1,
    defaultRightPins: 1,
    awgRange: [12, 20],
    options: ["ATO/ATC fuse holder", "Mini blade fuse holder"],
  },
  {
    id: "sleeve",
    label: "Sleeve / jacket",
    defaultLabel: "Protective sleeve",
    allowedLeftPins: [1, 2, 3, 4, 5, 6],
    allowedRightPins: [1, 2, 3, 4, 5, 6],
    defaultLeftPins: 2,
    defaultRightPins: 2,
    awgRange: [10, 32],
    options: ["PET braided sleeve", "Split loom", "Heatshrink sleeve"],
  },
];

export const wireTypes = [
  {
    id: "silicone",
    label: "Silicone",
    gauges: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    colors: ["Black", "Red", "White", "Blue", "Yellow", "Green"],
    notes: "Flexible wire for compact routing and small harness assemblies.",
  },
  {
    id: "ul1007",
    label: "UL1007 PVC hook-up",
    gauges: [16, 18, 20, 22, 24, 26, 28],
    colors: ["Black", "Red", "White", "Blue", "Yellow", "Green", "Orange"],
    notes: "Common internal equipment wire.",
  },
  {
    id: "txl",
    label: "TXL / GXL automotive",
    gauges: [12, 14, 16, 18, 20, 22],
    colors: ["Black", "Red", "White", "Blue", "Yellow", "Green", "Brown"],
    notes: "Vehicle and outdoor equipment harnesses.",
  },
  {
    id: "ptfe",
    label: "PTFE high-temp",
    gauges: [18, 20, 22, 24, 26, 28, 30],
    colors: ["Black", "Red", "White", "Blue", "Yellow"],
    notes: "High temperature or chemical exposure review basis.",
  },
];

export const defaultConnectorPartId = "adafruit-5978";
export const defaultWireTypeId = "silicone";

export function connectorPartById(partId) {
  return connectorParts.find((part) => part.id === partId) || connectorParts[0];
}

export function connectorFamilyById(familyId) {
  return connectorFamilies.find((family) => family.id === familyId) || connectorFamilies[0];
}

export function partsForFamily(familyId) {
  return connectorParts.filter((part) => part.familyId === familyId);
}

export function midElementTypeById(typeId) {
  return midElementTypes.find((type) => type.id === typeId) || midElementTypes[0];
}

export function wireTypeById(typeId) {
  return wireTypes.find((type) => type.id === typeId) || wireTypes[0];
}
