export const harnessCatalogVersion = "maker-robotics-catalog-2026-06-v1";

const colors = {
  signal: ["Black", "Red", "White", "Blue", "Yellow", "Green", "Orange", "Brown", "Gray", "Purple"],
  power: ["Black", "Red", "Yellow", "Blue", "Green"],
  qwiic: ["Black", "Red", "Blue", "Yellow"],
};

function family({
  id,
  manufacturer,
  name,
  category,
  defaultPartId,
  pitchMm = null,
  sealed = false,
  terminalPriceCents,
  laborProfile = "crimp",
  commonUse = "",
  sourceUrl = "",
}) {
  return {
    id,
    manufacturer,
    name,
    category,
    pitchMm,
    sealed,
    defaultPartId,
    terminalPriceCents,
    laborProfile,
    commonUse,
    sourceUrl,
  };
}

function connectorPart({
  id,
  mpn,
  manufacturer,
  familyId,
  displayName,
  pinCount,
  options,
  awgRange,
  currentRatingA,
  voltageRatingV,
  internalPriceCents,
  terminalPriceCents,
  compatibleTerminals,
  notes,
  visual = "rect-housing",
  pitchMm = null,
  sourceUrl = "",
  terminationStyle = "crimp",
}) {
  return {
    id,
    mpn,
    manufacturer,
    familyId,
    displayName,
    pinCounts: [pinCount],
    defaultPinCount: pinCount,
    options,
    awgRange,
    currentRatingA,
    voltageRatingV,
    internalPriceCents,
    terminalPriceCents,
    compatibleTerminals,
    notes,
    visual,
    pitchMm,
    sourceUrl,
    terminationStyle,
  };
}

function pinSeriesParts({
  idPrefix,
  idForPin,
  manufacturer,
  familyId,
  mpnForPin,
  displayName,
  pinCounts,
  options,
  awgRange,
  currentRatingA,
  voltageRatingV,
  basePriceCents,
  pinAdderCents,
  terminalPriceCents,
  compatibleTerminals,
  notes,
  visual = "rect-housing",
  pitchMm = null,
  sourceUrl = "",
}) {
  return pinCounts.map((pinCount) => {
    const mpn = mpnForPin(pinCount);
    return connectorPart({
      id: idForPin ? idForPin(pinCount, mpn) : `${idPrefix}-${pinCount}p`,
      mpn,
      manufacturer,
      familyId,
      displayName: `${displayName}, ${pinCount} pin`,
      pinCount,
      options,
      awgRange,
      currentRatingA,
      voltageRatingV,
      internalPriceCents: basePriceCents + pinCount * pinAdderCents,
      terminalPriceCents,
      compatibleTerminals,
      notes,
      visual,
      pitchMm,
      sourceUrl,
    });
  });
}

export const connectorFamilies = [
  family({
    id: "jst-sh",
    manufacturer: "JST",
    name: "SH / Qwiic-STEMMA QT",
    category: "Maker sensor / I2C",
    pitchMm: 1,
    defaultPartId: "jst-shr-04v-s-b",
    terminalPriceCents: 6,
    commonUse: "Qwiic, STEMMA QT, compact sensor boards",
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=231",
  }),
  family({
    id: "jst-ph",
    manufacturer: "JST",
    name: "PH",
    category: "Battery / board-to-wire",
    pitchMm: 2,
    defaultPartId: "jst-phr-2",
    terminalPriceCents: 7,
    commonUse: "Small batteries, compact robotics, sensor power leads",
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=199",
  }),
  family({
    id: "jst-xh",
    manufacturer: "JST",
    name: "XH",
    category: "Wire-to-board",
    pitchMm: 2.5,
    defaultPartId: "jst-xhp-4",
    terminalPriceCents: 7,
    commonUse: "3D printers, chargers, control boards, low-current equipment",
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=277",
  }),
  family({
    id: "jst-gh",
    manufacturer: "JST",
    name: "GH",
    category: "Locking wire-to-board",
    pitchMm: 1.25,
    defaultPartId: "jst-ghr-04v-s",
    terminalPriceCents: 9,
    commonUse: "Drones, compact robots, secured sensor harnesses",
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=105",
  }),
  family({
    id: "molex-picoblade",
    manufacturer: "Molex",
    name: "PicoBlade",
    category: "Compact wire-to-board",
    pitchMm: 1.25,
    defaultPartId: "molex-51021-0400",
    terminalPriceCents: 10,
    commonUse: "Small consumer electronics, drones, compact sensors",
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/picoblade-connectors",
  }),
  family({
    id: "molex-kk-254",
    manufacturer: "Molex",
    name: "KK 254",
    category: "2.54 mm board connector",
    pitchMm: 2.54,
    defaultPartId: "molex-22-01-2047",
    terminalPriceCents: 8,
    commonUse: "Arduino-era boards, arcade controls, pin-header signal harnesses",
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/kk-connectors",
  }),
  family({
    id: "molex-microfit-3",
    manufacturer: "Molex",
    name: "Micro-Fit 3.0",
    category: "Compact power connector",
    pitchMm: 3,
    defaultPartId: "molex-43025-0400",
    terminalPriceCents: 18,
    commonUse: "Robotics power, device internals, power plus signal",
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/micro-fit-connectors",
  }),
  family({
    id: "molex-minifit-jr",
    manufacturer: "Molex",
    name: "Mini-Fit Jr.",
    category: "Higher-current power connector",
    pitchMm: 4.2,
    defaultPartId: "molex-39-01-2040",
    terminalPriceCents: 30,
    commonUse: "Robotics power, PC-style power leads, embedded power distribution",
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/mini-fit-connectors",
  }),
  family({
    id: "te-amp-mini-ct",
    manufacturer: "TE Connectivity",
    name: "AMP Mini CT",
    category: "Miniature wire-to-board",
    pitchMm: 1.5,
    defaultPartId: "te-353908-4",
    terminalPriceCents: 10,
    commonUse: "Small consumer electronics, LED modules, compact board harnesses",
    sourceUrl: "https://www.te.com/en/products/connectors/pcb-connectors/wire-to-board-connectors/intersection/1-5mm-amp-mini-ct-connectors.html",
  }),
  family({
    id: "te-amp-ct",
    manufacturer: "TE Connectivity",
    name: "AMP CT",
    category: "2.0 mm wire-to-board",
    pitchMm: 2,
    defaultPartId: "te-179228-4",
    terminalPriceCents: 11,
    commonUse: "Consumer devices, appliance modules, board-to-wire harnesses",
    sourceUrl: "https://www.te.com/en/products/connectors/pcb-connectors/wire-to-board-connectors/intersection/2mm-amp-ct-connectors.html",
  }),
  family({
    id: "te-micro-mate-n-lok",
    manufacturer: "TE Connectivity",
    name: "Micro MATE-N-LOK",
    category: "Power connector",
    pitchMm: 3,
    defaultPartId: "te-1445022-4",
    terminalPriceCents: 24,
    commonUse: "Device power, lighting, appliances, robotics modules",
    sourceUrl: "https://www.te.com/en/products/connectors/rectangular-connectors/intersection/3mm-low-profile-micro-mate-n-lok-connectors.html",
  }),
  family({
    id: "te-ampmodu-mte",
    manufacturer: "TE Connectivity",
    name: "AMPMODU MTE",
    category: "2.54 mm crimp receptacle",
    pitchMm: 2.54,
    defaultPartId: "te-104257-3",
    terminalPriceCents: 15,
    commonUse: "Prototype boards, dev kits, single-row 0.1 inch headers",
    sourceUrl: "https://www.te.com/en/products/brands/ampmodu/ampmodumte.html",
  }),
  family({
    id: "seeed-grove",
    manufacturer: "Seeed Studio",
    name: "Grove 4-pin",
    category: "Maker sensor ecosystem",
    pitchMm: 2,
    defaultPartId: "seeed-grove-4p-buckled-4p",
    terminalPriceCents: 8,
    commonUse: "Grove sensor modules and quick prototypes",
    sourceUrl: "https://wiki.seeedstudio.com/Grove_System/",
  }),
  family({
    id: "dfrobot-gravity",
    manufacturer: "DFRobot",
    name: "Gravity PH2.0",
    category: "Maker sensor ecosystem",
    pitchMm: 2,
    defaultPartId: "dfrobot-gravity-ph20-3p-3p",
    terminalPriceCents: 8,
    commonUse: "DFRobot Gravity sensors, Arduino/robotics projects",
    sourceUrl: "https://www.dfrobot.com/product-2551.html",
  }),
  family({
    id: "usb-breakout",
    manufacturer: "Adafruit",
    name: "USB Breakout",
    category: "Board / breakout",
    defaultPartId: "adafruit-5978",
    terminalPriceCents: 12,
    laborProfile: "solder",
    commonUse: "USB-C pigtails, board breakouts, quick device adapters",
  }),
  family({
    id: "harwin-m20",
    manufacturer: "Harwin",
    name: "DuPont / M20",
    category: "2.54 mm crimp housing",
    pitchMm: 2.54,
    defaultPartId: "harwin-m20-1060300",
    terminalPriceCents: 14,
    commonUse: "Breadboard, dev-board, and 0.1 inch header harnesses",
    sourceUrl: "https://www.harwin.com/products/M20-8760742",
  }),
  family({
    id: "xt-power",
    manufacturer: "Amass",
    name: "XT power",
    category: "Soldered DC power",
    defaultPartId: "amass-xt30u-f-2p",
    terminalPriceCents: 18,
    laborProfile: "solder",
    commonUse: "Battery and motor-controller leads for drones and robots",
  }),
  family({
    id: "anderson-powerpole-15-45",
    manufacturer: "Anderson Power",
    name: "Powerpole 15/45",
    category: "Power connector",
    defaultPartId: "anderson-1327g6-bk",
    terminalPriceCents: 110,
    commonUse: "Low-voltage DC power and modular power leads",
    sourceUrl: "https://www.andersonpower.com/product-lines/powerpole/",
  }),
  family({
    id: "deutsch-dt",
    manufacturer: "TE / Deutsch",
    name: "DT sealed",
    category: "Sealed connector",
    sealed: true,
    defaultPartId: "deutsch-dt04-2p",
    terminalPriceCents: 95,
    commonUse: "Outdoor and vehicle-adjacent harnesses; v1 keeps this lower priority",
  }),
];

export const connectorParts = [
  ...pinSeriesParts({
    idPrefix: "jst-shr-04v-s-b",
    idForPin: (_pins, mpn) => `jst-${mpn.toLowerCase()}`,
    manufacturer: "JST",
    familyId: "jst-sh",
    mpnForPin: (pins) => `SHR-${String(pins).padStart(2, "0")}V-S-B`,
    displayName: "SH cable-side receptacle housing",
    pinCounts: [2, 3, 4, 5, 6],
    options: ["Cable-side receptacle", "Qwiic/STEMMA QT compatible on 4 pin"],
    awgRange: [28, 32],
    currentRatingA: 1,
    voltageRatingV: 50,
    basePriceCents: 14,
    pinAdderCents: 3,
    terminalPriceCents: 6,
    compatibleTerminals: ["SSH-003T-P0.2-H contact"],
    notes: "1.0 mm pitch; use 4 pin for Qwiic/STEMMA QT harnesses.",
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=231",
  }),
  connectorPart({
    id: "jst-sm04b-srss-tb-4p",
    mpn: "SM04B-SRSS-TB",
    manufacturer: "JST",
    familyId: "jst-sh",
    displayName: "SH 4-pin right-angle board header",
    pinCount: 4,
    options: ["Board header mate", "Qwiic/STEMMA QT board connector"],
    awgRange: [28, 32],
    currentRatingA: 1,
    voltageRatingV: 50,
    internalPriceCents: 32,
    terminalPriceCents: 12,
    compatibleTerminals: [],
    notes: "Board-side header endpoint; harness wire is normally terminated to SHR cable housing.",
    visual: "rect-housing",
    pitchMm: 1,
    sourceUrl: "https://www.sparkfun.com/qwiic-jst-connector-smd-4-pin-horizontal.html",
    terminationStyle: "solder",
  }),
  ...pinSeriesParts({
    idPrefix: "jst-phr",
    idForPin: (_pins, mpn) => `jst-${mpn.toLowerCase()}`,
    manufacturer: "JST",
    familyId: "jst-ph",
    mpnForPin: (pins) => `PHR-${pins}`,
    displayName: "PH receptacle housing",
    pinCounts: [2, 3, 4, 5, 6, 8],
    options: ["Cable-side receptacle", "Natural housing"],
    awgRange: [24, 30],
    currentRatingA: 2,
    voltageRatingV: 100,
    basePriceCents: 15,
    pinAdderCents: 4,
    terminalPriceCents: 7,
    compatibleTerminals: ["SPH-002T-P0.5S contact"],
    notes: "2.0 mm pitch compact power and signal connector.",
    pitchMm: 2,
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=199",
  }),
  ...pinSeriesParts({
    idPrefix: "jst-xhp",
    idForPin: (_pins, mpn) => `jst-${mpn.toLowerCase()}`,
    manufacturer: "JST",
    familyId: "jst-xh",
    mpnForPin: (pins) => `XHP-${pins}`,
    displayName: "XH receptacle housing",
    pinCounts: [2, 3, 4, 5, 6, 7, 8],
    options: ["Cable-side receptacle", "Natural housing"],
    awgRange: [22, 30],
    currentRatingA: 3,
    voltageRatingV: 250,
    basePriceCents: 16,
    pinAdderCents: 5,
    terminalPriceCents: 7,
    compatibleTerminals: ["SXH-001T-P0.6 contact"],
    notes: "2.5 mm pitch; common on chargers, printers, and control boards.",
    pitchMm: 2.5,
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=277",
  }),
  connectorPart({
    id: "jst-b6b-xh-a",
    mpn: "B6B-XH-A(LF)(SN)",
    manufacturer: "JST",
    familyId: "jst-xh",
    displayName: "XH 6-pin top-entry board header",
    pinCount: 6,
    options: ["Top-entry board header", "Natural housing mate"],
    awgRange: [22, 30],
    currentRatingA: 3,
    voltageRatingV: 250,
    internalPriceCents: 26,
    terminalPriceCents: 12,
    compatibleTerminals: [],
    notes: "Board header endpoint; direct wire attachment is treated as solder/board work.",
    pitchMm: 2.5,
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=277",
    terminationStyle: "solder",
  }),
  ...pinSeriesParts({
    idPrefix: "jst-ghr",
    idForPin: (_pins, mpn) => `jst-${mpn.toLowerCase()}`,
    manufacturer: "JST",
    familyId: "jst-gh",
    mpnForPin: (pins) => `GHR-${String(pins).padStart(2, "0")}V-S`,
    displayName: "GH locking receptacle housing",
    pinCounts: [2, 3, 4, 5, 6, 8],
    options: ["Cable-side locking receptacle", "Natural housing"],
    awgRange: [26, 30],
    currentRatingA: 1,
    voltageRatingV: 50,
    basePriceCents: 22,
    pinAdderCents: 5,
    terminalPriceCents: 9,
    compatibleTerminals: ["SSHL-002T-P0.2 contact"],
    notes: "1.25 mm pitch locking connector for compact electronics.",
    pitchMm: 1.25,
    sourceUrl: "https://www.jst-mfg.com/product/detail_e.php?series=105",
  }),
  ...pinSeriesParts({
    idPrefix: "molex-51021-0",
    idForPin: (_pins, mpn) => `molex-${mpn.toLowerCase()}`,
    manufacturer: "Molex",
    familyId: "molex-picoblade",
    mpnForPin: (pins) => `51021-0${pins}00`,
    displayName: "PicoBlade receptacle housing",
    pinCounts: [2, 3, 4, 5, 6],
    options: ["Cable-side receptacle", "Friction lock"],
    awgRange: [26, 32],
    currentRatingA: 1,
    voltageRatingV: 125,
    basePriceCents: 24,
    pinAdderCents: 6,
    terminalPriceCents: 10,
    compatibleTerminals: ["Molex PicoBlade crimp terminal"],
    notes: "1.25 mm pitch compact Molex connector.",
    pitchMm: 1.25,
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/picoblade-connectors",
  }),
  ...pinSeriesParts({
    idPrefix: "molex-22-01-20",
    idForPin: (_pins, mpn) => `molex-${mpn.toLowerCase()}`,
    manufacturer: "Molex",
    familyId: "molex-kk-254",
    mpnForPin: (pins) => `22-01-${String(2000 + pins * 10 + 7).padStart(4, "0")}`,
    displayName: "KK 254 crimp housing",
    pinCounts: [2, 3, 4, 6, 8],
    options: ["Cable-side housing", "0.1 inch pitch"],
    awgRange: [22, 30],
    currentRatingA: 5,
    voltageRatingV: 250,
    basePriceCents: 20,
    pinAdderCents: 5,
    terminalPriceCents: 8,
    compatibleTerminals: ["KK 254 crimp terminal"],
    notes: "2.54 mm pitch housing for square-pin board headers.",
    pitchMm: 2.54,
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/kk-connectors",
  }),
  ...pinSeriesParts({
    idPrefix: "molex-43025",
    idForPin: (_pins, mpn) => `molex-${mpn.toLowerCase()}`,
    manufacturer: "Molex",
    familyId: "molex-microfit-3",
    mpnForPin: (pins) => `43025-${String(pins).padStart(2, "0")}00`,
    displayName: "Micro-Fit 3.0 receptacle housing",
    pinCounts: [2, 4, 6, 8],
    options: ["Dual-row receptacle housing", "Black"],
    awgRange: [18, 30],
    currentRatingA: 8.5,
    voltageRatingV: 600,
    basePriceCents: 42,
    pinAdderCents: 12,
    terminalPriceCents: 18,
    compatibleTerminals: ["Micro-Fit 3.0 crimp terminal"],
    notes: "3.0 mm pitch power/signal connector.",
    visual: "microfit",
    pitchMm: 3,
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/micro-fit-connectors",
  }),
  ...pinSeriesParts({
    idPrefix: "molex-39-01",
    idForPin: (_pins, mpn) => `molex-${mpn.toLowerCase()}`,
    manufacturer: "Molex",
    familyId: "molex-minifit-jr",
    mpnForPin: (pins) => `39-01-${String(2000 + pins * 10).padStart(4, "0")}`,
    displayName: "Mini-Fit Jr. receptacle housing",
    pinCounts: [2, 4, 6, 8],
    options: ["Dual-row receptacle housing", "Natural housing"],
    awgRange: [16, 28],
    currentRatingA: 9,
    voltageRatingV: 600,
    basePriceCents: 62,
    pinAdderCents: 18,
    terminalPriceCents: 30,
    compatibleTerminals: ["Mini-Fit Jr. crimp terminal"],
    notes: "4.2 mm pitch higher-current wire-to-wire or wire-to-board family.",
    visual: "microfit",
    pitchMm: 4.2,
    sourceUrl: "https://www.molex.com/en-us/products/connectors/wire-to-board-connectors/mini-fit-connectors",
  }),
  ...pinSeriesParts({
    idPrefix: "te-353908",
    idForPin: (_pins, mpn) => `te-${mpn.toLowerCase()}`,
    manufacturer: "TE Connectivity",
    familyId: "te-amp-mini-ct",
    mpnForPin: (pins) => `353908-${pins}`,
    displayName: "AMP Mini CT receptacle housing",
    pinCounts: [2, 3, 4, 6, 8],
    options: ["Cable-side receptacle", "White housing"],
    awgRange: [24, 28],
    currentRatingA: 2,
    voltageRatingV: 50,
    basePriceCents: 18,
    pinAdderCents: 5,
    terminalPriceCents: 10,
    compatibleTerminals: ["353907-series socket contact"],
    notes: "1.5 mm pitch miniature wire-to-board housing.",
    pitchMm: 1.5,
    sourceUrl: "https://www.te.com/en/product-353908-2.html",
  }),
  ...pinSeriesParts({
    idPrefix: "te-179228",
    idForPin: (_pins, mpn) => `te-${mpn.toLowerCase()}`,
    manufacturer: "TE Connectivity",
    familyId: "te-amp-ct",
    mpnForPin: (pins) => `179228-${pins}`,
    displayName: "AMP CT receptacle housing",
    pinCounts: [2, 3, 4, 6, 8],
    options: ["Cable-side receptacle", "Natural housing"],
    awgRange: [22, 28],
    currentRatingA: 4,
    voltageRatingV: 125,
    basePriceCents: 22,
    pinAdderCents: 6,
    terminalPriceCents: 11,
    compatibleTerminals: ["AMP CT crimp contact"],
    notes: "2.0 mm pitch wire-to-board and wire-to-wire family.",
    pitchMm: 2,
    sourceUrl: "https://www.te.com/en/product-179228-2.html",
  }),
  ...pinSeriesParts({
    idPrefix: "te-1445022",
    idForPin: (_pins, mpn) => `te-${mpn.toLowerCase()}`,
    manufacturer: "TE Connectivity",
    familyId: "te-micro-mate-n-lok",
    mpnForPin: (pins) => `1445022-${pins}`,
    displayName: "Micro MATE-N-LOK receptacle housing",
    pinCounts: [2, 4, 6, 8, 10, 12],
    options: ["Single-row receptacle housing", "Positive latch"],
    awgRange: [18, 30],
    currentRatingA: 5,
    voltageRatingV: 250,
    basePriceCents: 48,
    pinAdderCents: 13,
    terminalPriceCents: 24,
    compatibleTerminals: ["Micro MATE-N-LOK crimp contact"],
    notes: "3.0 mm pitch positive-latch power connector.",
    visual: "microfit",
    pitchMm: 3,
    sourceUrl: "https://www.te.com/en/product-1445022-2.html",
  }),
  ...pinSeriesParts({
    idPrefix: "te-104257",
    idForPin: (_pins, mpn) => `te-${mpn.toLowerCase()}`,
    manufacturer: "TE Connectivity",
    familyId: "te-ampmodu-mte",
    mpnForPin: (pins) => `104257-${pins - 1}`,
    displayName: "AMPMODU MTE receptacle housing",
    pinCounts: [2, 3, 4, 5, 6, 8],
    options: ["Single-row receptacle", "0.1 inch pitch"],
    awgRange: [20, 32],
    currentRatingA: 3,
    voltageRatingV: 250,
    basePriceCents: 34,
    pinAdderCents: 7,
    terminalPriceCents: 15,
    compatibleTerminals: ["AMPMODU MTE crimp contact"],
    notes: "2.54 mm pitch modular crimp receptacle for prototype boards.",
    pitchMm: 2.54,
    sourceUrl: "https://www.te.com/en/products/brands/ampmodu/ampmodumte.html",
  }),
  connectorPart({
    id: "seeed-grove-4p-buckled-4p",
    mpn: "Grove-4P-2.0",
    manufacturer: "Seeed Studio",
    familyId: "seeed-grove",
    displayName: "Grove 4-pin buckled connector",
    pinCount: 4,
    options: ["Grove 4-pin 2.0 mm", "Sensor cable endpoint"],
    awgRange: [24, 28],
    currentRatingA: 1,
    voltageRatingV: 50,
    internalPriceCents: 38,
    terminalPriceCents: 8,
    compatibleTerminals: ["Grove 2.0 mm crimp terminal"],
    notes: "Grove ecosystem 4-pin connector; exact mate is selected by module.",
    pitchMm: 2,
    sourceUrl: "https://wiki.seeedstudio.com/Grove_System/",
  }),
  connectorPart({
    id: "dfrobot-gravity-ph20-3p-3p",
    mpn: "Gravity-PH2.0-3P",
    manufacturer: "DFRobot",
    familyId: "dfrobot-gravity",
    displayName: "Gravity PH2.0 3-pin sensor plug",
    pinCount: 3,
    options: ["3-pin digital sensor cable", "PH2.0 to DuPont style"],
    awgRange: [24, 28],
    currentRatingA: 1,
    voltageRatingV: 50,
    internalPriceCents: 42,
    terminalPriceCents: 8,
    compatibleTerminals: ["PH2.0 crimp terminal"],
    notes: "DFRobot Gravity-style 3-pin sensor endpoint.",
    pitchMm: 2,
    sourceUrl: "https://www.dfrobot.com/product-2551.html",
  }),
  connectorPart({
    id: "dfrobot-gravity-ph20-4p-4p",
    mpn: "Gravity-PH2.0-4P",
    manufacturer: "DFRobot",
    familyId: "dfrobot-gravity",
    displayName: "Gravity PH2.0 4-pin I2C/UART plug",
    pinCount: 4,
    options: ["4-pin I2C/UART sensor cable", "PH2.0 to DuPont style"],
    awgRange: [24, 28],
    currentRatingA: 1,
    voltageRatingV: 50,
    internalPriceCents: 48,
    terminalPriceCents: 8,
    compatibleTerminals: ["PH2.0 crimp terminal"],
    notes: "DFRobot Gravity-style 4-pin sensor endpoint.",
    pitchMm: 2,
    sourceUrl: "https://www.dfrobot.com/product-2554.html",
  }),
  connectorPart({
    id: "adafruit-5978",
    mpn: "5978",
    manufacturer: "Adafruit",
    familyId: "usb-breakout",
    displayName: "USB Type-C breakout",
    pinCount: 5,
    options: ["USB Type-C breakout", "USB 2.0 signal pads"],
    awgRange: [22, 28],
    currentRatingA: 1,
    voltageRatingV: 5,
    internalPriceCents: 495,
    terminalPriceCents: 12,
    compatibleTerminals: [],
    notes: "Breakout board pads use soldered leads.",
    visual: "usb-board",
    terminationStyle: "solder",
  }),
  connectorPart({
    id: "adafruit-5180",
    mpn: "5180",
    manufacturer: "Adafruit",
    familyId: "usb-breakout",
    displayName: "USB-C plug breakout",
    pinCount: 6,
    options: ["USB-C plug breakout", "Signal pads"],
    awgRange: [24, 30],
    currentRatingA: 1,
    voltageRatingV: 5,
    internalPriceCents: 695,
    terminalPriceCents: 12,
    compatibleTerminals: [],
    notes: "USB-C plug breakout for soldered leads.",
    visual: "usb-board",
    terminationStyle: "solder",
  }),
  connectorPart({
    id: "adafruit-6050",
    mpn: "6050",
    manufacturer: "Adafruit",
    familyId: "usb-breakout",
    displayName: "USB-C receptacle breakout",
    pinCount: 6,
    options: ["USB-C receptacle breakout", "Power-only pads"],
    awgRange: [24, 30],
    currentRatingA: 1,
    voltageRatingV: 5,
    internalPriceCents: 450,
    terminalPriceCents: 12,
    compatibleTerminals: [],
    notes: "USB-C receptacle breakout for soldered leads.",
    visual: "usb-board",
    terminationStyle: "solder",
  }),
  ...pinSeriesParts({
    idPrefix: "harwin-m20-106",
    idForPin: (_pins, mpn) => `harwin-${mpn.toLowerCase()}`,
    manufacturer: "Harwin",
    familyId: "harwin-m20",
    mpnForPin: (pins) => `M20-106${String(pins).padStart(2, "0")}00`,
    displayName: "M20 1-row female crimp housing",
    pinCounts: [2, 3, 4, 5, 6, 8],
    options: ["1 row female crimp housing", "Black"],
    awgRange: [22, 30],
    currentRatingA: 3,
    voltageRatingV: 250,
    basePriceCents: 24,
    pinAdderCents: 4,
    terminalPriceCents: 14,
    compatibleTerminals: ["M20 crimp socket contact"],
    notes: "Common 2.54 mm pitch housing for pin-header harnesses.",
    pitchMm: 2.54,
    sourceUrl: "https://www.harwin.com/products/M20-8760742",
  }),
  connectorPart({
    id: "amass-xt30u-f-2p",
    mpn: "XT30U-F",
    manufacturer: "Amass",
    familyId: "xt-power",
    displayName: "XT30 female solder connector",
    pinCount: 2,
    options: ["Female battery connector", "Solder cup"],
    awgRange: [14, 18],
    currentRatingA: 15,
    voltageRatingV: 500,
    internalPriceCents: 110,
    terminalPriceCents: 18,
    compatibleTerminals: [],
    notes: "Soldered RC-style power connector; current basis is conservative continuous use.",
    visual: "powerpole",
    terminationStyle: "solder",
  }),
  connectorPart({
    id: "amass-xt30u-m-2p",
    mpn: "XT30U-M",
    manufacturer: "Amass",
    familyId: "xt-power",
    displayName: "XT30 male solder connector",
    pinCount: 2,
    options: ["Male battery connector", "Solder cup"],
    awgRange: [14, 18],
    currentRatingA: 15,
    voltageRatingV: 500,
    internalPriceCents: 110,
    terminalPriceCents: 18,
    compatibleTerminals: [],
    notes: "Soldered RC-style power connector; current basis is conservative continuous use.",
    visual: "powerpole",
    terminationStyle: "solder",
  }),
  connectorPart({
    id: "amass-xt60-f-2p",
    mpn: "XT60-F",
    manufacturer: "Amass",
    familyId: "xt-power",
    displayName: "XT60 female solder connector",
    pinCount: 2,
    options: ["Female battery connector", "Solder cup"],
    awgRange: [12, 16],
    currentRatingA: 30,
    voltageRatingV: 500,
    internalPriceCents: 165,
    terminalPriceCents: 24,
    compatibleTerminals: [],
    notes: "Soldered power connector for higher-current robot battery leads.",
    visual: "powerpole",
    terminationStyle: "solder",
  }),
  connectorPart({
    id: "amass-xt60-m-2p",
    mpn: "XT60-M",
    manufacturer: "Amass",
    familyId: "xt-power",
    displayName: "XT60 male solder connector",
    pinCount: 2,
    options: ["Male battery connector", "Solder cup"],
    awgRange: [12, 16],
    currentRatingA: 30,
    voltageRatingV: 500,
    internalPriceCents: 165,
    terminalPriceCents: 24,
    compatibleTerminals: [],
    notes: "Soldered power connector for higher-current robot battery leads.",
    visual: "powerpole",
    terminationStyle: "solder",
  }),
  connectorPart({
    id: "anderson-1327g6-bk",
    mpn: "1327G6-BK",
    manufacturer: "Anderson Power",
    familyId: "anderson-powerpole-15-45",
    displayName: "Powerpole 15/45 housing, black",
    pinCount: 1,
    options: ["1 row, neutral, black"],
    awgRange: [10, 20],
    currentRatingA: 45,
    voltageRatingV: 600,
    internalPriceCents: 85,
    terminalPriceCents: 110,
    compatibleTerminals: ["Powerpole 15/30/45 contacts"],
    notes: "Often paired with red housing for DC power.",
    visual: "powerpole",
    sourceUrl: "https://www.andersonpower.com/product-lines/powerpole/",
  }),
  connectorPart({
    id: "anderson-1327g6-red",
    mpn: "1327G6-RED",
    manufacturer: "Anderson Power",
    familyId: "anderson-powerpole-15-45",
    displayName: "Powerpole 15/45 housing, red",
    pinCount: 1,
    options: ["1 row, neutral, red"],
    awgRange: [10, 20],
    currentRatingA: 45,
    voltageRatingV: 600,
    internalPriceCents: 85,
    terminalPriceCents: 110,
    compatibleTerminals: ["Powerpole 15/30/45 contacts"],
    notes: "Often paired with black housing for DC power.",
    visual: "powerpole",
    sourceUrl: "https://www.andersonpower.com/product-lines/powerpole/",
  }),
  connectorPart({
    id: "deutsch-dt04-2p",
    mpn: "DT04-2P",
    manufacturer: "TE / Deutsch",
    familyId: "deutsch-dt",
    displayName: "DT 2-pin receptacle housing",
    pinCount: 2,
    options: ["Receptacle, 2 pin, gray", "Wedge lock needed"],
    awgRange: [14, 20],
    currentRatingA: 13,
    voltageRatingV: 250,
    internalPriceCents: 185,
    terminalPriceCents: 95,
    compatibleTerminals: ["Size 16 solid contacts", "W2P wedge lock"],
    notes: "Seals and wedge locks are included in the internal catalog basis.",
    visual: "sealed-dt",
  }),
];

export const midElementTypes = [
  {
    id: "splice",
    label: "Solder splice",
    defaultLabel: "Solder splice, black heatshrink",
    allowedLeftPins: [1, 2, 3, 4],
    allowedRightPins: [1, 2, 3, 4],
    defaultLeftPins: 1,
    defaultRightPins: 4,
    awgRange: [10, 32],
    options: ["Black heatshrink", "Clear heatshrink", "Adhesive-lined heatshrink"],
    materialPriceCents: 60,
    laborPriceCents: 160,
  },
  {
    id: "cable",
    label: "Cable breakout",
    defaultLabel: "Cable breakout",
    allowedLeftPins: [1, 2, 3, 4, 5, 6],
    allowedRightPins: [1, 2, 3, 4, 5, 6],
    defaultLeftPins: 1,
    defaultRightPins: 2,
    awgRange: [18, 30],
    options: ["Jacketed cable", "Shielded cable", "Twisted pair"],
    materialPriceCents: 180,
    laborPriceCents: 220,
  },
  {
    id: "fuse",
    label: "Inline fuse",
    defaultLabel: "Inline fuse holder",
    allowedLeftPins: [1],
    allowedRightPins: [1],
    defaultLeftPins: 1,
    defaultRightPins: 1,
    awgRange: [12, 20],
    options: ["ATO/ATC fuse holder", "Mini blade fuse holder"],
    materialPriceCents: 325,
    laborPriceCents: 180,
  },
  {
    id: "sleeve",
    label: "Sleeve / jacket",
    defaultLabel: "Protective sleeve",
    allowedLeftPins: [1, 2, 3, 4, 5, 6],
    allowedRightPins: [1, 2, 3, 4, 5, 6],
    defaultLeftPins: 2,
    defaultRightPins: 2,
    awgRange: [10, 32],
    options: ["PET braided sleeve", "Split loom", "Heatshrink sleeve"],
    materialPriceCents: 120,
    laborPriceCents: 110,
  },
  {
    id: "shield_drain",
    label: "Shield drain",
    defaultLabel: "Shield drain termination",
    allowedLeftPins: [1, 2],
    allowedRightPins: [1, 2],
    defaultLeftPins: 1,
    defaultRightPins: 1,
    awgRange: [22, 30],
    options: ["Drain wire to ground", "Foil shield termination"],
    materialPriceCents: 95,
    laborPriceCents: 190,
  },
  {
    id: "branch_point",
    label: "Branch point",
    defaultLabel: "Labeled branch point",
    allowedLeftPins: [1, 2, 3, 4, 5, 6],
    allowedRightPins: [1, 2, 3, 4, 5, 6],
    defaultLeftPins: 2,
    defaultRightPins: 3,
    awgRange: [18, 30],
    options: ["Heatshrink branch", "Sleeved branch", "Labeled branch"],
    materialPriceCents: 140,
    laborPriceCents: 240,
  },
];

export const wireTypes = [
  {
    id: "silicone",
    label: "Silicone",
    gauges: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    colors: colors.power.concat(["White", "Orange"]),
    notes: "Flexible wire for compact routing and robot battery/device leads.",
    pricePerMeterCentsByGauge: { 10: 410, 12: 318, 14: 232, 16: 168, 18: 126, 20: 96, 22: 72, 24: 54, 26: 44, 28: 36, 30: 30 },
  },
  {
    id: "ul1007",
    label: "UL1007 PVC hook-up",
    gauges: [16, 18, 20, 22, 24, 26, 28],
    colors: colors.signal,
    notes: "Common internal equipment wire.",
    pricePerMeterCentsByGauge: { 16: 72, 18: 56, 20: 44, 22: 34, 24: 28, 26: 24, 28: 20 },
  },
  {
    id: "qwiic-stemma",
    label: "Qwiic/STEMMA QT color set",
    gauges: [26, 28, 30],
    colors: colors.qwiic,
    notes: "Small signal wire colors used for Qwiic/STEMMA QT style harnesses.",
    pricePerMeterCentsByGauge: { 26: 46, 28: 38, 30: 32 },
  },
  {
    id: "ribbon",
    label: "IDC / ribbon lead",
    gauges: [26, 28, 30],
    colors: ["Gray", "Rainbow", "Black", "Red"],
    notes: "Flat or grouped signal wire for 0.1 inch prototype connections.",
    pricePerMeterCentsByGauge: { 26: 38, 28: 32, 30: 28 },
  },
  {
    id: "shielded-signal",
    label: "Shielded signal",
    gauges: [22, 24, 26, 28],
    colors: ["Black", "Gray", "Blue"],
    notes: "Shielded or drain-supported signal routing where noise control matters.",
    pricePerMeterCentsByGauge: { 22: 126, 24: 96, 26: 78, 28: 64 },
  },
  {
    id: "txl",
    label: "TXL / GXL automotive",
    gauges: [12, 14, 16, 18, 20, 22],
    colors: ["Black", "Red", "White", "Blue", "Yellow", "Green", "Brown"],
    notes: "Vehicle and outdoor equipment harnesses; lower priority for v1.",
    pricePerMeterCentsByGauge: { 12: 118, 14: 92, 16: 70, 18: 52, 20: 42, 22: 34 },
  },
  {
    id: "ptfe",
    label: "PTFE high-temp",
    gauges: [18, 20, 22, 24, 26, 28, 30],
    colors: ["Black", "Red", "White", "Blue", "Yellow"],
    notes: "High temperature or chemical exposure routing.",
    pricePerMeterCentsByGauge: { 18: 188, 20: 148, 22: 112, 24: 88, 26: 72, 28: 58, 30: 48 },
  },
];

export const defaultConnectorPartId = "jst-shr-04v-s-b";
export const defaultWireTypeId = "silicone";

export function connectorPartById(partId) {
  return connectorParts.find((part) => part.id === partId) || connectorParts[0];
}

export function connectorFamilyById(familyId) {
  return connectorFamilies.find((item) => item.id === familyId) || connectorFamilies[0];
}

export function partsForFamily(familyId) {
  return connectorParts
    .filter((part) => part.familyId === familyId)
    .sort((a, b) => a.defaultPinCount - b.defaultPinCount || a.mpn.localeCompare(b.mpn));
}

export function partForFamilyPinCount(familyId, pinCount) {
  const parts = partsForFamily(familyId);
  return parts.find((part) => part.pinCounts.includes(Number(pinCount))) || parts[0] || connectorParts[0];
}

export function midElementTypeById(typeId) {
  return midElementTypes.find((type) => type.id === typeId) || midElementTypes[0];
}

export function wireTypeById(typeId) {
  return wireTypes.find((type) => type.id === typeId) || wireTypes[0];
}
