-- Real persistence correction.
-- 1) Request numbers are generated by the database, not by browser state.
-- 2) Quote confirmation creates/returns a real persisted order; no local-only success path.

create or replace function public.create_request_with_number(
  p_customer_label text,
  p_title text,
  p_customer_summary text,
  p_status text,
  p_check_status text,
  p_check_result jsonb,
  p_files_count integer
)
returns public.requests
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year text := to_char(now(), 'YYYY');
  v_next integer;
  v_number text;
  v_request public.requests%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  -- One request number sequence for the current year. The lock prevents two
  -- simultaneous submissions from receiving the same visible request number.
  perform pg_advisory_xact_lock(hashtext('easy_harness_request_number_' || v_year));

  select coalesce(
    max((regexp_match(request_number, '^HD-' || v_year || '-([0-9]+)-A$'))[1]::integer),
    1049
  ) + 1
  into v_next
  from public.requests
  where request_number ~ ('^HD-' || v_year || '-[0-9]+-A$');

  v_number := 'HD-' || v_year || '-' || v_next::text || '-A';

  insert into public.requests (
    request_number,
    customer_id,
    customer_label,
    title,
    status,
    customer_summary,
    check_status,
    check_result,
    files_count
  )
  values (
    v_number,
    auth.uid(),
    coalesce(nullif(p_customer_label, ''), 'Customer'),
    coalesce(nullif(p_title, ''), 'Uploaded Harness Design Request'),
    coalesce(nullif(p_status, ''), 'checking'),
    coalesce(p_customer_summary, ''),
    coalesce(nullif(p_check_status, ''), 'pending'),
    coalesce(p_check_result, '{}'::jsonb),
    coalesce(p_files_count, 0)
  )
  returning * into v_request;

  return v_request;
end;
$$;

grant execute on function public.create_request_with_number(
  text,
  text,
  text,
  text,
  text,
  jsonb,
  integer
) to authenticated;

create or replace function public.confirm_request_order(
  p_request_id uuid,
  p_quote_id uuid,
  p_order_number text,
  p_title text,
  p_harness_price numeric,
  p_shipping_price numeric,
  p_total_due numeric,
  p_currency char(3),
  p_address jsonb,
  p_snapshot jsonb,
  p_package_estimate jsonb,
  p_production_lead_time text,
  p_estimated_production_complete date
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.requests%rowtype;
  v_quote public.quotes%rowtype;
  v_order public.orders%rowtype;
begin
  select *
  into v_request
  from public.requests
  where id = p_request_id
    and customer_id = auth.uid()
  for update;

  if not found then
    raise exception 'Request not found';
  end if;

  select *
  into v_quote
  from public.quotes
  where id = p_quote_id
    and request_id = p_request_id
    and status in ('released', 'confirmed')
  for update;

  if not found then
    raise exception 'Released quote not found';
  end if;

  if v_request.active_quote_id is distinct from p_quote_id
     and v_request.confirmed_quote_id is distinct from p_quote_id then
    raise exception 'Quote is not active';
  end if;

  select *
  into v_order
  from public.orders
  where request_id = p_request_id
    and quote_id = p_quote_id
  order by created_at desc
  limit 1;

  if found then
    update public.requests
    set
      status = 'confirmed',
      confirmed_quote_id = p_quote_id,
      updated_at = now()
    where id = p_request_id;

    update public.quotes
    set status = 'confirmed'
    where id = p_quote_id;

    return v_order;
  end if;

  if v_request.status not in ('ready_to_confirm', 'confirmed') then
    raise exception 'Request is not ready to confirm';
  end if;

  update public.quotes
  set status = 'confirmed'
  where id = p_quote_id;

  update public.requests
  set
    status = 'confirmed',
    confirmed_quote_id = p_quote_id,
    updated_at = now()
  where id = p_request_id;

  insert into public.orders (
    order_number,
    request_id,
    customer_id,
    quote_id,
    title,
    status,
    payment_status,
    fulfillment_status,
    production_status,
    harness_price,
    shipping_price,
    total_due,
    currency,
    incoterm,
    address,
    snapshot,
    package_estimate,
    production_lead_time,
    estimated_production_complete
  )
  values (
    p_order_number,
    p_request_id,
    v_request.customer_id,
    p_quote_id,
    coalesce(nullif(p_title, ''), v_request.title),
    'checkout',
    'unpaid',
    'not_shipped',
    'checkout',
    coalesce(p_harness_price, v_quote.amount),
    coalesce(p_shipping_price, 0),
    coalesce(p_total_due, coalesce(p_harness_price, v_quote.amount) + coalesce(p_shipping_price, 0)),
    coalesce(p_currency, v_quote.currency),
    'DAP',
    coalesce(p_address, '{}'::jsonb),
    coalesce(p_snapshot, '{}'::jsonb),
    coalesce(p_package_estimate, '{}'::jsonb),
    coalesce(p_production_lead_time, ''),
    p_estimated_production_complete
  )
  on conflict (order_number) do update
  set
    updated_at = now()
  returning * into v_order;

  return v_order;
end;
$$;

grant execute on function public.confirm_request_order(
  uuid,
  uuid,
  text,
  text,
  numeric,
  numeric,
  numeric,
  char(3),
  jsonb,
  jsonb,
  jsonb,
  text,
  date
) to authenticated;
